### ISSUE TITLE
mochaFile option doesn't work

### ISSUE THREAD

**Issue by dramamask** [michaelleeallen/mocha-junit-reporter#107]
I upgraded from version 1.18.0 to 1.23.2, and the mochaFile option didn't work anymore. Instead writing to the designated folder and filename, a generic "test-results.xml" file was created in the root.

I use the mocha file option like this in my package.json file: "--reporter-options mochaFile=./path_to_your/file.xml"

**Comment by clayreimann** [comment]
Should be resolved with 1.23.3

**Comment by goyney** [comment]
I am on 1.23.3, this issue is still a thing. Mocha 7.1.0.

```
reporterOptions: {
  mochaFile: '../reports/contract.xml'
},
```

A generic `test-results.xml` file is created every time.

**Comment by qooban** [comment]
I had the same issue in my cypress configuration (using `cypress-multi-reporters` with `mocha-junit-reporter`) when I upgraded to the latest `mocha-junit-version` `v1.23.3`.

With `v1.23.0` it works fine and uses `mochaFile` field.
